os:
  - linux

services:
  - docker

before_install: 
  - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in CICD/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - cp CICD/ssh_config ~/.ssh/

script:
  - docker build -t cyetstar/proxy-pool -f Docker/Dockerfile .
  
after_success:
  - echo $DOCKER_1AGAIN_PASSWORD | docker login -u cyetstar --password-stdin
  - docker push cyetstar/proxy-pool

deploy:
  provider: script
  script: bash CICD/Scripts/deploy.sh
  on:
    branch: develop